name: Autopilot

on:
  schedule:
    - cron: '0 9 1 * *'
  workflow_dispatch:

permissions: read-all

jobs:
  autopilot:
    permissions:
      contents: write
      pull-requests: write
    uses: byteworthyllc/.github/.github/workflows/reusable-autopilot.yml@ff712b79b7139b35f2475928db2c1dd0c85f7477
    with:
      stack: both
      auto_merge: true
